apiVersion: 1

datasources:
  - name: IntelliPay Metrics
    type: prometheus
    uid: intellipay-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
  - name: IntelliPay Traces
    type: jaeger
    uid: intellipay-jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false